### ISSUE TITLE
openshift stop

### ISSUE THREAD

**Issue by nullifye** [ilbonte/node-telegram-bot-starter-kit#1]
hi, thanks for the guide..

my app stopped because there is no open port (8080)...

how to solve this?

**Comment by ilbonte** [comment]
As i wrote [here](https://github.com/ilbonte/node-telegram-bot-starter-kit#deploy) also if you get a failure when you deploy your application (like in the immage below) your bot will work (if your javascript code is correct)
![image](https://cloud.githubusercontent.com/assets/7412876/13246658/e68dc304-da0c-11e5-9d69-cebb467d318c.png)

**Comment by nullifye** [comment]
thank you for the reply..

my bad. i'm using coffee style that trigger the error. 
all working now
